"""3D Analysis public API.

This namespace contains same-sample, multi-slice Xenium contour workflows.
It includes conservative TPS soft alignment for a hard-aligned contour pair
and pyXenium-backed multi-slice contour stack reconstruction.
"""

from __future__ import annotations

from .soft_alignment import (
    ThreeDContourReconstructionConfig,
    ThreeDContourReconstructionResult,
    ThreeDFeatureUnavailableError,
    run_3d_contour_reconstruction,
)
from .image_registration import (
    CODA_METHOD_CREDIT,
    CODA_METHOD_REFERENCE_DOI,
    CODA_METHOD_REFERENCE_URL,
    CODA_METHODOLOGY_URL,
    CodaImageRegistrationConfig,
    CodaImageRegistrationResult,
    RadonRotationResult,
    TranslationResult,
    apply_similarity_to_points,
    estimate_coda_image_registration,
    estimate_radon_rotation,
    estimate_translation,
)
from .multislice import (
    ThreeDStackReconstructionConfig,
    ThreeDStackReconstructionResult,
    discover_xenium_slices,
    hard_align_geojson,
    reconstruct_3d_contour_meshes,
    run_3d_stack_reconstruction,
    write_3d_contour_points,
    write_3d_visualization_html,
)
from .label_free_alignment import (
    AnchorOnlyResidualTPSConfig,
    AnchorOnlyResidualTPSResult,
    IterativeContourRefinementConfig,
    IterativeContourRefinementResult,
    LabelFreeContourAlignmentConfig,
    LabelFreeContourAlignmentResult,
    align_contours_label_free,
    run_anchor_only_residual_tps,
    run_iterative_contour_refinement,
)
from .label_free_figure import (
    LabelFreeBeforeAfterFigureConfig,
    LabelFreeBeforeAfterFigureResult,
    render_label_free_before_after_panel,
)
from .tear_aware_alignment import (
    ContourTearClosureConfig,
    ContourTearClosureResult,
    run_contour_tear_closure,
)
from .cell_cloud import (
    CELL_CLOUD_ALIGNED_XY_OBSM_KEY,
    CELL_CLOUD_OBS_SLICE_KEY,
    CELL_CLOUD_OBSM_KEY,
    CELL_CLOUD_UNS_KEY,
    CellCloudProjectionConfig,
    CellCloudProjectionResult,
    CellCloudRenderConfig,
    CellCloudRenderResult,
    build_alignment_manifest,
    cell_cloud_cache_status,
    cell_cloud_dataframe_from_coordinates,
    hash_alignment_manifest,
    load_cell_alignment_transforms,
    project_cell_coordinates,
    render_cell_cloud_html,
    run_cell_cloud_projection,
    write_cell_cloud_cache,
)
from .local_z_orientation import (
    LOCAL_Z_ORIENTATION_SCHEMA_VERSION,
    LOCAL_Z_ORIENTATION_STATES,
    LocalZOrientationConfig,
    LocalZOrientationResult,
    run_local_z_orientation_correction,
)
from .gland_qc import (
    GlandQCAtlasConfig,
    GlandQCAtlasResult,
    render_gland_qc_atlas,
)
from .gland_instances import (
    DEFAULT_EPITHELIAL_MARKERS,
    DEFAULT_EPITHELIAL_STRUCTURES,
    GlandInstanceSegmentationConfig,
    GlandInstanceSegmentationResult,
    segment_gland_instances,
)
from .gland_tracking import (
    GlandInstanceTrackingConfig,
    GlandInstanceTrackingResult,
    track_gland_instances,
)
from .gland_atlas import (
    GlandInstanceAtlasResult,
    GlandInstanceDetectionResult,
    render_gland_instance_atlas,
    run_gland_instance_detection,
)
from .gland_position_atlas import (
    GlandPositionAtlasConfig,
    GlandPositionAtlasResult,
    render_gland_position_atlas,
)
from .gland_surface_atlas import (
    GlandSurfaceAtlasConfig,
    GlandSurfaceAtlasResult,
    render_gland_surface_atlas,
)
from .gland_biology import (
    BOUNDARY_INTERACTIONS,
    SIGNATURES,
    GlandBiologyMiningConfig,
    GlandBiologyMiningResult,
    run_gland_biology_mining,
)
from .spatial_modules import (
    GeneStructureQuantificationConfig,
    GeneStructureQuantificationResult,
    SpatialModuleDiscoveryConfig,
    SpatialModuleDiscoveryResult,
    SpatialModulePlotConfig,
    SpatialModulePlotResult,
    compute_hotspot_overlap_metrics,
    compute_hotspot_sdf_metrics,
    plot_spatial_module_clustermap,
    quantify_gene_structure_relationships,
    run_spatial_module_discovery,
)
from .spatialdata_export import (
    SpatialData3DExportConfig,
    SpatialData3DExportResult,
    export_stack_to_spatialdata_3d,
)

__all__ = [
    "CELL_CLOUD_ALIGNED_XY_OBSM_KEY",
    "CELL_CLOUD_OBS_SLICE_KEY",
    "CELL_CLOUD_OBSM_KEY",
    "CELL_CLOUD_UNS_KEY",
    "BOUNDARY_INTERACTIONS",
    "CODA_METHOD_CREDIT",
    "CODA_METHOD_REFERENCE_DOI",
    "CODA_METHOD_REFERENCE_URL",
    "CODA_METHODOLOGY_URL",
    "CellCloudProjectionConfig",
    "CellCloudProjectionResult",
    "CellCloudRenderConfig",
    "CellCloudRenderResult",
    "CodaImageRegistrationConfig",
    "CodaImageRegistrationResult",
    "ContourTearClosureConfig",
    "ContourTearClosureResult",
    "DEFAULT_EPITHELIAL_MARKERS",
    "DEFAULT_EPITHELIAL_STRUCTURES",
    "GeneStructureQuantificationConfig",
    "GeneStructureQuantificationResult",
    "GlandBiologyMiningConfig",
    "GlandBiologyMiningResult",
    "GlandInstanceAtlasResult",
    "GlandInstanceDetectionResult",
    "GlandInstanceSegmentationConfig",
    "GlandInstanceSegmentationResult",
    "GlandInstanceTrackingConfig",
    "GlandInstanceTrackingResult",
    "GlandPositionAtlasConfig",
    "GlandPositionAtlasResult",
    "GlandQCAtlasConfig",
    "GlandQCAtlasResult",
    "GlandSurfaceAtlasConfig",
    "GlandSurfaceAtlasResult",
    "AnchorOnlyResidualTPSConfig",
    "AnchorOnlyResidualTPSResult",
    "IterativeContourRefinementConfig",
    "IterativeContourRefinementResult",
    "LabelFreeContourAlignmentConfig",
    "LabelFreeContourAlignmentResult",
    "LabelFreeBeforeAfterFigureConfig",
    "LabelFreeBeforeAfterFigureResult",
    "LOCAL_Z_ORIENTATION_SCHEMA_VERSION",
    "LOCAL_Z_ORIENTATION_STATES",
    "LocalZOrientationConfig",
    "LocalZOrientationResult",
    "RadonRotationResult",
    "SIGNATURES",
    "SpatialModuleDiscoveryConfig",
    "SpatialModuleDiscoveryResult",
    "SpatialModulePlotConfig",
    "SpatialModulePlotResult",
    "SpatialData3DExportConfig",
    "SpatialData3DExportResult",
    "ThreeDContourReconstructionConfig",
    "ThreeDContourReconstructionResult",
    "ThreeDFeatureUnavailableError",
    "ThreeDStackReconstructionConfig",
    "ThreeDStackReconstructionResult",
    "TranslationResult",
    "align_contours_label_free",
    "apply_similarity_to_points",
    "compute_hotspot_overlap_metrics",
    "compute_hotspot_sdf_metrics",
    "build_alignment_manifest",
    "cell_cloud_cache_status",
    "cell_cloud_dataframe_from_coordinates",
    "discover_xenium_slices",
    "estimate_coda_image_registration",
    "estimate_radon_rotation",
    "estimate_translation",
    "export_stack_to_spatialdata_3d",
    "hard_align_geojson",
    "hash_alignment_manifest",
    "load_cell_alignment_transforms",
    "plot_spatial_module_clustermap",
    "project_cell_coordinates",
    "quantify_gene_structure_relationships",
    "reconstruct_3d_contour_meshes",
    "render_cell_cloud_html",
    "render_label_free_before_after_panel",
    "run_contour_tear_closure",
    "render_gland_instance_atlas",
    "render_gland_position_atlas",
    "render_gland_qc_atlas",
    "render_gland_surface_atlas",
    "run_3d_contour_reconstruction",
    "run_anchor_only_residual_tps",
    "run_iterative_contour_refinement",
    "run_cell_cloud_projection",
    "run_gland_biology_mining",
    "run_gland_instance_detection",
    "run_local_z_orientation_correction",
    "run_spatial_module_discovery",
    "run_3d_stack_reconstruction",
    "segment_gland_instances",
    "track_gland_instances",
    "write_3d_contour_points",
    "write_3d_visualization_html",
    "write_cell_cloud_cache",
]
